### ISSUE TITLE
Not seeing the path for the leap motion SDK

### ISSUE THREAD

**Issue by flipsidecreations** [rpav/xleapmouse#3]
## When I run the ./configure I fails to see that I have installed the LeapMotion SDK.  Is there a work around or a place I can just copy the SDK files to?

checking Leap.h usability... no
checking Leap.h presence... no
checking for Leap.h... no

**Comment by rpav** [comment]
Some more detail?  Your dist, have you looked in /usr/lib/Leap, etc...

(Apparently I didn't update the faq with "it can't find my Leap.h"...)

**Comment by flipsidecreations** [comment]
Ubuntu 14.10 and all seems to be in place at /usr/lib/Leap/  the rest of the build up to that point seems fine.

**Comment by rpav** [comment]
Yeah try using `LIBLEAP_CPPFLAGS` and `LIBLEAP_LDFLAGS` to make it look there, probably with `-I` and `-L` parameters.  Alternatively you could symlink the .so and .h to the "right" places, but that's probably not the best approach.

If nothing else, if you could post an `ls -lR` of that I can probably point you at what you need.  It'd be nice to add these to the code as well.

**Comment by flipsidecreations** [comment]
here is the list of files.  I am using the latest version of the SDK

lrwxrwxrwx 1 root root       19 Apr 13 15:44 libQt5Core.so.5 -> libQt5Core.so.5.2.1
-rw-r--r-- 1 root root 32277760 Apr 13 15:44 libQt5Core.so.5.2.1
lrwxrwxrwx 1 root root       19 Apr 13 15:44 libQt5DBus.so.5 -> libQt5DBus.so.5.2.1
-rw-r--r-- 1 root root   527896 Apr 13 15:44 libQt5DBus.so.5.2.1
lrwxrwxrwx 1 root root       18 Apr 13 15:44 libQt5Gui.so.5 -> libQt5Gui.so.5.2.1
-rw-r--r-- 1 root root  4719792 Apr 13 15:44 libQt5Gui.so.5.2.1
lrwxrwxrwx 1 root root       25 Apr 13 15:44 libQt5Multimedia.so.5 -> libQt5Multimedia.so.5.2.1
-rw-r--r-- 1 root root   899792 Apr 13 15:44 libQt5Multimedia.so.5.2.1
lrwxrwxrwx 1 root root       32 Apr 13 15:44 libQt5MultimediaWidgets.so.5 -> libQt5MultimediaWidgets.so.5.2.1
-rw-r--r-- 1 root root   120064 Apr 13 15:44 libQt5MultimediaWidgets.so.5.2.1
lrwxrwxrwx 1 root root       22 Apr 13 15:44 libQt5Network.so.5 -> libQt5Network.so.5.2.1
-rw-r--r-- 1 root root  3343024 Apr 13 15:44 libQt5Network.so.5.2.1
lrwxrwxrwx 1 root root       21 Apr 13 15:44 libQt5OpenGL.so.5 -> libQt5OpenGL.so.5.2.1
-rw-r--r-- 1 root root   406152 Apr 13 15:44 libQt5OpenGL.so.5.2.1
lrwxrwxrwx 1 root root       26 Apr 13 15:44 libQt5Positioning.so.5 -> libQt5Positioning.so.5.2.1
-rw-r--r-- 1 root root   241928 Apr 13 15:44 libQt5Positioning.so.5.2.1
lrwxrwxrwx 1 root root       27 Apr 13 15:44 libQt5PrintSupport.so.5 -> libQt5PrintSupport.so.5.2.1
-rw-r--r-- 1 root root   352752 Apr 13 15:44 libQt5PrintSupport.so.5.2.1
lrwxrwxrwx 1 root root       18 Apr 13 15:44 libQt5Qml.so.5 -> libQt5Qml.so.5.2.1
-rw-r--r-- 1 root root  4250760 Apr 13 15:44 libQt5Qml.so.5.2.1
lrwxrwxrwx 1 root root       20 Apr 13 15:44 libQt5Quick.so.5 -> libQt5Quick.so.5.2.1
-rw-r--r-- 1 root root  3742032 Apr 13 15:44 libQt5Quick.so.5.2.1
lrwxrwxrwx 1 root root       21 Apr 13 15:44 libQt5Script.so.5 -> libQt5Script.so.5.2.1
-rw-r--r-- 1 root root  2470344 Apr 13 15:44 libQt5Script.so.5.2.1
lrwxrwxrwx 1 root root       22 Apr 13 15:44 libQt5Sensors.so.5 -> libQt5Sensors.so.5.2.1
-rw-r--r-- 1 root root   247400 Apr 13 15:44 libQt5Sensors.so.5.2.1
lrwxrwxrwx 1 root root       18 Apr 13 15:44 libQt5Sql.so.5 -> libQt5Sql.so.5.2.1
-rw-r--r-- 1 root root   257928 Apr 13 15:44 libQt5Sql.so.5.2.1
lrwxrwxrwx 1 root root       21 Apr 13 15:44 libQt5WebKit.so.5 -> libQt5WebKit.so.5.2.1
-rw-r--r-- 1 root root 35743152 Apr 13 15:44 libQt5WebKit.so.5.2.1
lrwxrwxrwx 1 root root       28 Apr 13 15:44 libQt5WebKitWidgets.so.5 -> libQt5WebKitWidgets.so.5.2.1
-rw-r--r-- 1 root root   287176 Apr 13 15:44 libQt5WebKitWidgets.so.5.2.1
lrwxrwxrwx 1 root root       22 Apr 13 15:44 libQt5Widgets.so.5 -> libQt5Widgets.so.5.2.1
-rw-r--r-- 1 root root  6389816 Apr 13 15:44 libQt5Widgets.so.5.2.1
-rw-r--r-- 1 root root    94544 Apr 13 15:44 libusb-1.0.so.0

**Comment by rpav** [comment]
There is in fact no `libLeap.so` there... I'd list the .deb and see where everything lives.

**Comment by rpav** [comment]
Note my guess is you may have /usr/lib/libLeap.so which is "obviously available," but if headers live in e.g. `/usr/include/Leap` you need to have `LIBLEAP_CPPFLAGS="-I/usr/include/Leap"`.

**Comment by flipsidecreations** [comment]
Thanks, I try that!

**Comment by thijsterlouw** [comment]
same issue (Ubuntu 14 as well). With the help above, I solved it by 

1. symlinking the header files to /usr/include/Leap
2. symlinking libLeap.so to /usr/lib/Leap
3. using the following configure command:
```
./configure LIBLEAP_CPPFLAGS="-I/usr/include/Leap" LIBLEAP_LDFLAGS="-L/usr/lib/Leap"
```

**Comment by rpav** [comment]
Thanks. I should probably add a few additional checks (and really, switch to cmake).

**Comment by stevenroy** [comment]
I have the SDK installed, but I haven't been able to make this work, despite the suggestions above. I see that I am supposed to symlink the header files to /usr/include/Leap but I'm not able to find the header files for some reason (including with mlocate).

Could someone let me know where the header files usually live?

**Comment by rpav** [comment]
If you can't find the headers, you don't have the SDK installed (correctly, at least).  Note this is more than than the libraries required for the LeapMotion; you should have downloaded the SDK <a href="https://developer.leapmotion.com/">from LeapMotion directly</a>, since it's subject to their licensing terms.

If you did, query the package you installed to see where they went (and if you extracted the package, you should know where they went! ;).

**Comment by rpav** [comment]
This was rewritten with CMake at some point; if it's still an issue, feel free to reopen.
