### ISSUE TITLE
Not seeing the GUI/Docked icon

### ISSUE THREAD

**Issue by MikeRea95** [rpav/xleapmouse#4]
Hello!

I got your code installed on my Linux Mint 18.3 machine, and it runs, but I don't see the docked icon you describe in the Readme. Do you have any idea why this could be?

Thanks!

**Comment by rpav** [comment]
Probably it's not building with Qt support.  It's not necessary for running, but it is for the GUI and icon.

**Comment by rpav** [comment]
Note I recently upgraded to Mint 19 myself; prior I had issues with the SDK crashing.  Testing now, it seems to work fine.

**Comment by rpav** [comment]
Just updated this with rewritten build for cmake, which should much more reliably find Qt5 and build.

**Comment by rpav** [comment]
Please reopen if you still have an issue.
